import { RankingData } from './types';

export const MOCK_DATA: Record<string, RankingData[]> = {
  overall: [
    // A组
    { group: 'A组', rank: 1, region: '深莞区', yoy: 3.0, change: 1 },
    { group: 'A组', rank: 2, region: '北京区', yoy: 2.0, change: -2 },
    { group: 'A组', rank: 3, region: '广佛区', yoy: 1.0, change: 0 },
    { group: 'A组', rank: 4, region: '浙北区', yoy: -0.5, change: 0 },
    { group: 'A组', rank: 5, region: '上海区', yoy: 2.0, change: -2 },
    { group: 'A组', rank: 6, region: '苏南区', yoy: -1.0, change: 0 },
    // B组
    { group: 'B组', rank: 1, region: '湖北区', yoy: 2.0, change: 1 },
    { group: 'B组', rank: 2, region: '四川区', yoy: 2.0, change: -2 },
    { group: 'B组', rank: 3, region: '河南区', yoy: -2.5, change: -3 },
    { group: 'B组', rank: 4, region: '安徽区', yoy: 2.0, change: -4 },
    { group: 'B组', rank: 5, region: '辽宁区', yoy: 2.0, change: 0 },
    { group: 'B组', rank: 6, region: '福建区', yoy: 2.0, change: 0 },
    { group: 'B组', rank: 7, region: '河北', yoy: 2.0, change: 0 },
    // C组
    { group: 'C组', rank: 1, region: '粤西区', yoy: -2.5, change: 0 },
    { group: 'C组', rank: 2, region: '粤东区', yoy: 2.0, change: 0 },
    { group: 'C组', rank: 3, region: '浙南区', yoy: -2.5, change: -2 },
    { group: 'C组', rank: 4, region: '浙中区', yoy: 2.0, change: 0 },
    { group: 'C组', rank: 5, region: '苏中区', yoy: -2.5, change: 0 },
    { group: 'C组', rank: 6, region: '鲁西区', yoy: -1.0, change: -2 },
    { group: 'C组', rank: 7, region: '鲁东区', yoy: -0.5, change: 0 },
    { group: 'C组', rank: 8, region: '苏北区', yoy: 2.0, change: 0 },
    // D组
    { group: 'D组', rank: 1, region: '湖南区', yoy: -2.5, change: 0 },
    { group: 'D组', rank: 2, region: '江西区', yoy: -1.0, change: -2 },
    { group: 'D组', rank: 3, region: '云南区', yoy: -0.5, change: 0 },
    { group: 'D组', rank: 4, region: '重庆区', yoy: -2.5, change: 0 },
    { group: 'D组', rank: 5, region: '天津区', yoy: -1.0, change: -2 },
    { group: 'D组', rank: 6, region: '黑吉区', yoy: -0.5, change: 0 },
    { group: 'D组', rank: 7, region: '陕西区', yoy: 2.0, change: 0 },
    // E组
    { group: 'E组', rank: 1, region: '海南区', yoy: -2.5, change: 0 },
    { group: 'E组', rank: 2, region: '新疆区', yoy: -1.0, change: -2 },
    { group: 'E组', rank: 3, region: '山西区', yoy: -0.5, change: 0 },
    { group: 'E组', rank: 4, region: '广西区', yoy: -2.5, change: 0 },
    { group: 'E组', rank: 5, region: '甘青区', yoy: -1.0, change: -2 },
    { group: 'E组', rank: 6, region: '贵州区', yoy: -0.5, change: 0 },
    { group: 'E组', rank: 7, region: '内蒙古区', yoy: 2.0, change: 0 },
  ],
  small_package: [
    // A组
    { group: 'A组', rank: 1, region: '北京区', yoy: 5.2, change: 2 },
    { group: 'A组', rank: 2, region: '上海区', yoy: 4.8, change: 0 },
    { group: 'A组', rank: 3, region: '深莞区', yoy: 4.5, change: -2 },
    { group: 'A组', rank: 4, region: '广佛区', yoy: 3.2, change: 1 },
    { group: 'A组', rank: 5, region: '浙北区', yoy: 2.8, change: -1 },
    { group: 'A组', rank: 6, region: '苏南区', yoy: 1.5, change: 0 },
    // B组
    { group: 'B组', rank: 1, region: '四川区', yoy: 4.5, change: 3 },
    { group: 'B组', rank: 2, region: '湖北区', yoy: 4.2, change: 1 },
    { group: 'B组', rank: 3, region: '河南区', yoy: 3.8, change: -1 },
    { group: 'B组', rank: 4, region: '安徽区', yoy: 2.5, change: 0 },
    { group: 'B组', rank: 5, region: '辽宁区', yoy: 2.1, change: -2 },
    { group: 'B组', rank: 6, region: '福建区', yoy: 1.8, change: 0 },
    { group: 'B组', rank: 7, region: '河北', yoy: 1.2, change: 0 },
    // C组
    { group: 'C组', rank: 1, region: '浙中区', yoy: 3.9, change: 2 },
    { group: 'C组', rank: 2, region: '粤东区', yoy: 3.5, change: 0 },
    { group: 'C组', rank: 3, region: '苏北区', yoy: 3.2, change: 1 },
    { group: 'C组', rank: 4, region: '粤西区', yoy: 2.9, change: -1 },
    { group: 'C组', rank: 5, region: '浙南区', yoy: 2.5, change: -3 },
    { group: 'C组', rank: 6, region: '苏中区', yoy: 1.8, change: 0 },
    { group: 'C组', rank: 7, region: '鲁西区', yoy: 1.2, change: -2 },
    { group: 'C组', rank: 8, region: '鲁东区', yoy: 0.5, change: 0 },
    // D组
    { group: 'D组', rank: 1, region: '陕西区', yoy: 3.8, change: 4 },
    { group: 'D组', rank: 2, region: '湖南区', yoy: 3.2, change: 1 },
    { group: 'D组', rank: 3, region: '黑吉区', yoy: 2.8, change: 0 },
    { group: 'D组', rank: 4, region: '江西区', yoy: 2.5, change: -2 },
    { group: 'D组', rank: 5, region: '云南区', yoy: 1.9, change: -1 },
    { group: 'D组', rank: 6, region: '天津区', yoy: 1.2, change: 0 },
    { group: 'D组', rank: 7, region: '重庆区', yoy: 0.8, change: -3 },
    // E组
    { group: 'E组', rank: 1, region: '内蒙古区', yoy: 3.5, change: 2 },
    { group: 'E组', rank: 2, region: '海南区', yoy: 2.8, change: 0 },
    { group: 'E组', rank: 3, region: '广西区', yoy: 2.2, change: 1 },
    { group: 'E组', rank: 4, region: '山西区', yoy: 1.8, change: -1 },
    { group: 'E组', rank: 5, region: '新疆区', yoy: 1.2, change: -2 },
    { group: 'E组', rank: 6, region: '甘青区', yoy: 0.5, change: 0 },
    { group: 'E组', rank: 7, region: '贵州区', yoy: -0.2, change: 0 },
  ],
  individual_order: [
    // A组
    { group: 'A组', rank: 1, region: '广佛区', yoy: 6.1, change: 3 },
    { group: 'A组', rank: 2, region: '浙北区', yoy: 5.9, change: 1 },
    { group: 'A组', rank: 3, region: '苏南区', yoy: 5.5, change: -1 },
    { group: 'A组', rank: 4, region: '深莞区', yoy: 4.8, change: -2 },
    { group: 'A组', rank: 5, region: '北京区', yoy: 4.2, change: 0 },
    { group: 'A组', rank: 6, region: '上海区', yoy: 3.5, change: -1 },
    // B组
    { group: 'B组', rank: 1, region: '河南区', yoy: 5.2, change: 2 },
    { group: 'B组', rank: 2, region: '安徽区', yoy: 4.9, change: 0 },
    { group: 'B组', rank: 3, region: '福建区', yoy: 4.5, change: 1 },
    { group: 'B组', rank: 4, region: '湖北区', yoy: 4.1, change: -2 },
    { group: 'B组', rank: 5, region: '四川区', yoy: 3.8, change: -1 },
    { group: 'B组', rank: 6, region: '辽宁区', yoy: 3.2, change: 0 },
    { group: 'B组', rank: 7, region: '河北', yoy: 2.5, change: -1 },
    // C组
    { group: 'C组', rank: 1, region: '苏北区', yoy: 4.8, change: 3 },
    { group: 'C组', rank: 2, region: '浙南区', yoy: 4.5, change: -1 },
    { group: 'C组', rank: 3, region: '粤东区', yoy: 4.1, change: 0 },
    { group: 'C组', rank: 4, region: '鲁东区', yoy: 3.8, change: 2 },
    { group: 'C组', rank: 5, region: '浙中区', yoy: 3.2, change: -2 },
    { group: 'C组', rank: 6, region: '粤西区', yoy: 2.9, change: 0 },
    { group: 'C组', rank: 7, region: '苏中区', yoy: 2.5, change: -1 },
    { group: 'C组', rank: 8, region: '鲁西区', yoy: 1.8, change: -3 },
    // D组
    { group: 'D组', rank: 1, region: '江西区', yoy: 4.2, change: 0 },
    { group: 'D组', rank: 2, region: '黑吉区', yoy: 3.9, change: 1 },
    { group: 'D组', rank: 3, region: '陕西区', yoy: 3.5, change: 2 },
    { group: 'D组', rank: 4, region: '湖南区', yoy: 3.1, change: -2 },
    { group: 'D组', rank: 5, region: '云南区', yoy: 2.8, change: -1 },
    { group: 'D组', rank: 6, region: '重庆区', yoy: 2.2, change: 0 },
    { group: 'D组', rank: 7, region: '天津区', yoy: 1.5, change: -2 },
    // E组
    { group: 'E组', rank: 1, region: '新疆区', yoy: 3.8, change: -2 },
    { group: 'E组', rank: 2, region: '山西区', yoy: 3.5, change: 1 },
    { group: 'E组', rank: 3, region: '广西区', yoy: 3.1, change: 0 },
    { group: 'E组', rank: 4, region: '内蒙古区', yoy: 2.8, change: 2 },
    { group: 'E组', rank: 5, region: '甘青区', yoy: 2.2, change: -1 },
    { group: 'E组', rank: 6, region: '海南区', yoy: 1.8, change: 0 },
    { group: 'E组', rank: 7, region: '贵州区', yoy: 1.2, change: -1 },
  ],
  large_package: [
    // A组
    { group: 'A组', rank: 1, region: '上海区', yoy: 4.2, change: 1 },
    { group: 'A组', rank: 2, region: '北京区', yoy: 3.8, change: -1 },
    { group: 'A组', rank: 3, region: '深莞区', yoy: 3.5, change: 0 },
    { group: 'A组', rank: 4, region: '广佛区', yoy: 2.9, change: 2 },
    { group: 'A组', rank: 5, region: '浙北区', yoy: 2.5, change: -1 },
    { group: 'A组', rank: 6, region: '苏南区', yoy: 1.8, change: 0 },
    // B组
    { group: 'B组', rank: 1, region: '安徽区', yoy: 3.9, change: 2 },
    { group: 'B组', rank: 2, region: '河南区', yoy: 3.5, change: 0 },
    { group: 'B组', rank: 3, region: '湖北区', yoy: 3.2, change: 1 },
    { group: 'B组', rank: 4, region: '四川区', yoy: 2.8, change: -1 },
    { group: 'B组', rank: 5, region: '福建区', yoy: 2.5, change: -2 },
    { group: 'B组', rank: 6, region: '辽宁区', yoy: 1.8, change: 0 },
    { group: 'B组', rank: 7, region: '河北', yoy: 1.2, change: 0 },
    // C组
    { group: 'C组', rank: 1, region: '粤东区', yoy: 3.5, change: 1 },
    { group: 'C组', rank: 2, region: '苏北区', yoy: 3.2, change: 0 },
    { group: 'C组', rank: 3, region: '浙中区', yoy: 2.9, change: 2 },
    { group: 'C组', rank: 4, region: '粤西区', yoy: 2.5, change: -1 },
    { group: 'C组', rank: 5, region: '浙南区', yoy: 2.1, change: -2 },
    { group: 'C组', rank: 6, region: '苏中区', yoy: 1.5, change: 0 },
    { group: 'C组', rank: 7, region: '鲁西区', yoy: 0.8, change: -1 },
    { group: 'C组', rank: 8, region: '鲁东区', yoy: 0.2, change: 0 },
    // D组
    { group: 'D组', rank: 1, region: '黑吉区', yoy: 3.2, change: 2 },
    { group: 'D组', rank: 2, region: '江西区', yoy: 2.8, change: 0 },
    { group: 'D组', rank: 3, region: '陕西区', yoy: 2.5, change: 1 },
    { group: 'D组', rank: 4, region: '湖南区', yoy: 2.1, change: -1 },
    { group: 'D组', rank: 5, region: '云南区', yoy: 1.8, change: -2 },
    { group: 'D组', rank: 6, region: '重庆区', yoy: 1.2, change: 0 },
    { group: 'D组', rank: 7, region: '天津区', yoy: 0.5, change: -1 },
    // E组
    { group: 'E组', rank: 1, region: '山西区', yoy: 2.8, change: 1 },
    { group: 'E组', rank: 2, region: '新疆区', yoy: 2.5, change: 0 },
    { group: 'E组', rank: 3, region: '广西区', yoy: 2.1, change: 2 },
    { group: 'E组', rank: 4, region: '内蒙古区', yoy: 1.8, change: -1 },
    { group: 'E组', rank: 5, region: '甘青区', yoy: 1.2, change: -2 },
    { group: 'E组', rank: 6, region: '海南区', yoy: 0.5, change: 0 },
    { group: 'E组', rank: 7, region: '贵州区', yoy: -0.2, change: -1 },
  ],
  incentive_overall: [
    // A组
    { group: 'A组', rank: 1, region: '深莞区', yoy: 12.5, achievementRate: 102.5, achievementRank: 1, change: 0 },
    { group: 'A组', rank: 2, region: '北京区', yoy: 10.2, achievementRate: 98.2, achievementRank: 2, change: 1 },
    { group: 'A组', rank: 3, region: '广佛区', yoy: 9.8, achievementRate: 97.5, achievementRank: 3, change: -1 },
    { group: 'A组', rank: 4, region: '浙北区', yoy: 8.5, achievementRate: 95.2, achievementRank: 4, change: 0 },
    { group: 'A组', rank: 5, region: '上海区', yoy: 7.2, achievementRate: 92.8, achievementRank: 5, change: 0 },
    { group: 'A组', rank: 6, region: '苏南区', yoy: 6.5, achievementRate: 90.5, achievementRank: 6, change: 0 },
    // B组
    { group: 'B组', rank: 1, region: '湖北区', yoy: 11.2, achievementRate: 101.5, achievementRank: 1, change: 2 },
    { group: 'B组', rank: 2, region: '四川区', yoy: 9.5, achievementRate: 98.2, achievementRank: 2, change: 0 },
    { group: 'B组', rank: 3, region: '河南区', yoy: 8.8, achievementRate: 96.5, achievementRank: 3, change: -1 },
    { group: 'B组', rank: 4, region: '安徽区', yoy: 7.5, achievementRate: 94.2, achievementRank: 4, change: 0 },
    { group: 'B组', rank: 5, region: '辽宁区', yoy: 6.2, achievementRate: 92.8, achievementRank: 5, change: 0 },
    { group: 'B组', rank: 6, region: '福建区', yoy: 5.5, achievementRate: 90.5, achievementRank: 6, change: 0 },
    { group: 'B组', rank: 7, region: '河北', yoy: 4.8, achievementRate: 88.2, achievementRank: 7, change: 0 },
    // C组
    { group: 'C组', rank: 1, region: '粤西区', yoy: 10.8, achievementRate: 100.8, achievementRank: 1, change: 1 },
    { group: 'C组', rank: 2, region: '粤东区', yoy: 9.5, achievementRate: 98.2, achievementRank: 2, change: 0 },
    { group: 'C组', rank: 3, region: '浙南区', yoy: 8.8, achievementRate: 96.5, achievementRank: 3, change: -1 },
    { group: 'C组', rank: 4, region: '浙中区', yoy: 7.5, achievementRate: 94.2, achievementRank: 4, change: 0 },
    { group: 'C组', rank: 5, region: '苏中区', yoy: 6.2, achievementRate: 92.8, achievementRank: 5, change: 0 },
    { group: 'C组', rank: 6, region: '鲁西区', yoy: 5.5, achievementRate: 90.5, achievementRank: 6, change: 0 },
    { group: 'C组', rank: 7, region: '鲁东区', yoy: 4.8, achievementRate: 88.2, achievementRank: 7, change: 0 },
    { group: 'C组', rank: 8, region: '苏北区', yoy: 4.2, achievementRate: 86.5, achievementRank: 8, change: 0 },
    // D组
    { group: 'D组', rank: 1, region: '湖南区', yoy: 9.8, achievementRate: 99.5, achievementRank: 1, change: 0 },
    { group: 'D组', rank: 2, region: '江西区', yoy: 8.5, achievementRate: 97.2, achievementRank: 2, change: 0 },
    { group: 'D组', rank: 3, region: '云南区', yoy: 7.8, achievementRate: 95.5, achievementRank: 3, change: 0 },
    { group: 'D组', rank: 4, region: '重庆区', yoy: 6.5, achievementRate: 93.2, achievementRank: 4, change: 0 },
    { group: 'D组', rank: 5, region: '天津区', yoy: 5.2, achievementRate: 91.8, achievementRank: 5, change: 0 },
    { group: 'D组', rank: 6, region: '黑吉区', yoy: 4.5, achievementRate: 89.5, achievementRank: 6, change: 0 },
    { group: 'D组', rank: 7, region: '陕西区', yoy: 3.8, achievementRate: 87.2, achievementRank: 7, change: 0 },
    // E组
    { group: 'E组', rank: 1, region: '海南区', yoy: 8.8, achievementRate: 98.5, achievementRank: 1, change: 0 },
    { group: 'E组', rank: 2, region: '新疆区', yoy: 7.5, achievementRate: 96.2, achievementRank: 2, change: 0 },
    { group: 'E组', rank: 3, region: '山西区', yoy: 6.8, achievementRate: 94.5, achievementRank: 3, change: 0 },
    { group: 'E组', rank: 4, region: '广西区', yoy: 5.5, achievementRate: 92.2, achievementRank: 4, change: 0 },
    { group: 'E组', rank: 5, region: '甘青区', yoy: 4.2, achievementRate: 90.8, achievementRank: 5, change: 0 },
    { group: 'E组', rank: 6, region: '贵州区', yoy: 3.5, achievementRate: 88.5, achievementRank: 6, change: 0 },
    { group: 'E组', rank: 7, region: '内蒙古区', yoy: 2.8, achievementRate: 86.2, achievementRank: 7, change: 0 },
  ],
  incentive_large: [
    // A组
    { group: 'A组', rank: 1, region: '深莞区', yoy: 10.5, achievementRate: 101.5, achievementRank: 1, change: 0 },
    { group: 'A组', rank: 2, region: '北京区', yoy: 9.2, achievementRate: 97.2, achievementRank: 2, change: 1 },
    { group: 'A组', rank: 3, region: '广佛区', yoy: 8.8, achievementRate: 96.5, achievementRank: 3, change: -1 },
    { group: 'A组', rank: 4, region: '浙北区', yoy: 7.5, achievementRate: 94.2, achievementRank: 4, change: 0 },
    { group: 'A组', rank: 5, region: '上海区', yoy: 6.2, achievementRate: 91.8, achievementRank: 5, change: 0 },
    { group: 'A组', rank: 6, region: '苏南区', yoy: 5.5, achievementRate: 89.5, achievementRank: 6, change: 0 },
    // B组
    { group: 'B组', rank: 1, region: '湖北区', yoy: 9.2, achievementRate: 100.5, achievementRank: 1, change: 2 },
    { group: 'B组', rank: 2, region: '四川区', yoy: 8.5, achievementRate: 97.2, achievementRank: 2, change: 0 },
    { group: 'B组', rank: 3, region: '河南区', yoy: 7.8, achievementRate: 95.5, achievementRank: 3, change: -1 },
    { group: 'B组', rank: 4, region: '安徽区', yoy: 6.5, achievementRate: 93.2, achievementRank: 4, change: 0 },
    { group: 'B组', rank: 5, region: '辽宁区', yoy: 5.2, achievementRate: 91.8, achievementRank: 5, change: 0 },
    { group: 'B组', rank: 6, region: '福建区', yoy: 4.5, achievementRate: 89.5, achievementRank: 6, change: 0 },
    { group: 'B组', rank: 7, region: '河北', yoy: 3.8, achievementRate: 87.2, achievementRank: 7, change: 0 },
    // C组
    { group: 'C组', rank: 1, region: '粤西区', yoy: 8.8, achievementRate: 99.8, achievementRank: 1, change: 1 },
    { group: 'C组', rank: 2, region: '粤东区', yoy: 7.5, achievementRate: 97.2, achievementRank: 2, change: 0 },
    { group: 'C组', rank: 3, region: '浙南区', yoy: 6.8, achievementRate: 95.5, achievementRank: 3, change: -1 },
    { group: 'C组', rank: 4, region: '浙中区', yoy: 5.5, achievementRate: 93.2, achievementRank: 4, change: 0 },
    { group: 'C组', rank: 5, region: '苏中区', yoy: 4.2, achievementRate: 91.8, achievementRank: 5, change: 0 },
    { group: 'C组', rank: 6, region: '鲁西区', yoy: 3.5, achievementRate: 89.5, achievementRank: 6, change: 0 },
    { group: 'C组', rank: 7, region: '鲁东区', yoy: 2.8, achievementRate: 87.2, achievementRank: 7, change: 0 },
    { group: 'C组', rank: 8, region: '苏北区', yoy: 2.2, achievementRate: 85.5, achievementRank: 8, change: 0 },
    // D组
    { group: 'D组', rank: 1, region: '湖南区', yoy: 7.8, achievementRate: 98.5, achievementRank: 1, change: 0 },
    { group: 'D组', rank: 2, region: '江西区', yoy: 6.5, achievementRate: 96.2, achievementRank: 2, change: 0 },
    { group: 'D组', rank: 3, region: '云南区', yoy: 5.8, achievementRate: 94.5, achievementRank: 3, change: 0 },
    { group: 'D组', rank: 4, region: '重庆区', yoy: 4.5, achievementRate: 92.2, achievementRank: 4, change: 0 },
    { group: 'D组', rank: 5, region: '天津区', yoy: 3.2, achievementRate: 90.8, achievementRank: 5, change: 0 },
    { group: 'D组', rank: 6, region: '黑吉区', yoy: 2.5, achievementRate: 88.5, achievementRank: 6, change: 0 },
    { group: 'D组', rank: 7, region: '陕西区', yoy: 1.8, achievementRate: 86.2, achievementRank: 7, change: 0 },
    // E组
    { group: 'E组', rank: 1, region: '海南区', yoy: 6.8, achievementRate: 97.5, achievementRank: 1, change: 0 },
    { group: 'E组', rank: 2, region: '新疆区', yoy: 5.5, achievementRate: 95.2, achievementRank: 2, change: 0 },
    { group: 'E组', rank: 3, region: '山西区', yoy: 4.8, achievementRate: 93.5, achievementRank: 3, change: 0 },
    { group: 'E组', rank: 4, region: '广西区', yoy: 3.5, achievementRate: 91.2, achievementRank: 4, change: 0 },
    { group: 'E组', rank: 5, region: '甘青区', yoy: 2.2, achievementRate: 89.8, achievementRank: 5, change: 0 },
    { group: 'E组', rank: 6, region: '贵州区', yoy: 1.5, achievementRate: 87.5, achievementRank: 6, change: 0 },
    { group: 'E组', rank: 7, region: '内蒙古区', yoy: 0.8, achievementRate: 85.2, achievementRank: 7, change: 0 },
  ],
  incentive_small: [
    // A组
    { group: 'A组', rank: 1, region: '深莞区', yoy: 15.5, achievementRate: 103.5, achievementRank: 1, change: 0 },
    { group: 'A组', rank: 2, region: '北京区', yoy: 14.2, achievementRate: 100.2, achievementRank: 2, change: 1 },
    { group: 'A组', rank: 3, region: '广佛区', yoy: 13.8, achievementRate: 99.5, achievementRank: 3, change: -1 },
    { group: 'A组', rank: 4, region: '浙北区', yoy: 12.5, achievementRate: 97.2, achievementRank: 4, change: 0 },
    { group: 'A组', rank: 5, region: '上海区', yoy: 11.2, achievementRate: 95.8, achievementRank: 5, change: 0 },
    { group: 'A组', rank: 6, region: '苏南区', yoy: 10.5, achievementRate: 93.5, achievementRank: 6, change: 0 },
    // B组
    { group: 'B组', rank: 1, region: '湖北区', yoy: 14.2, achievementRate: 102.5, achievementRank: 1, change: 2 },
    { group: 'B组', rank: 2, region: '四川区', yoy: 13.5, achievementRate: 100.2, achievementRank: 2, change: 0 },
    { group: 'B组', rank: 3, region: '河南区', yoy: 12.8, achievementRate: 98.5, achievementRank: 3, change: -1 },
    { group: 'B组', rank: 4, region: '安徽区', yoy: 11.5, achievementRate: 96.2, achievementRank: 4, change: 0 },
    { group: 'B组', rank: 5, region: '辽宁区', yoy: 10.2, achievementRate: 94.8, achievementRank: 5, change: 0 },
    { group: 'B组', rank: 6, region: '福建区', yoy: 9.5, achievementRate: 92.5, achievementRank: 6, change: 0 },
    { group: 'B组', rank: 7, region: '河北', yoy: 8.8, achievementRate: 90.2, achievementRank: 7, change: 0 },
    // C组
    { group: 'C组', rank: 1, region: '粤西区', yoy: 13.8, achievementRate: 101.8, achievementRank: 1, change: 1 },
    { group: 'C组', rank: 2, region: '粤东区', yoy: 12.5, achievementRate: 100.2, achievementRank: 2, change: 0 },
    { group: 'C组', rank: 3, region: '浙南区', yoy: 11.8, achievementRate: 98.5, achievementRank: 3, change: -1 },
    { group: 'C组', rank: 4, region: '浙中区', yoy: 10.5, achievementRate: 96.2, achievementRank: 4, change: 0 },
    { group: 'C组', rank: 5, region: '苏中区', yoy: 9.2, achievementRate: 94.8, achievementRank: 5, change: 0 },
    { group: 'C组', rank: 6, region: '鲁西区', yoy: 8.5, achievementRate: 92.5, achievementRank: 6, change: 0 },
    { group: 'C组', rank: 7, region: '鲁东区', yoy: 7.8, achievementRate: 90.2, achievementRank: 7, change: 0 },
    { group: 'C组', rank: 8, region: '苏北区', yoy: 7.2, achievementRate: 88.5, achievementRank: 8, change: 0 },
    // D组
    { group: 'D组', rank: 1, region: '湖南区', yoy: 12.8, achievementRate: 101.5, achievementRank: 1, change: 0 },
    { group: 'D组', rank: 2, region: '江西区', yoy: 11.5, achievementRate: 99.2, achievementRank: 2, change: 0 },
    { group: 'D组', rank: 3, region: '云南区', yoy: 10.8, achievementRate: 97.5, achievementRank: 3, change: 0 },
    { group: 'D组', rank: 4, region: '重庆区', yoy: 9.5, achievementRate: 95.2, achievementRank: 4, change: 0 },
    { group: 'D组', rank: 5, region: '天津区', yoy: 8.2, achievementRate: 93.8, achievementRank: 5, change: 0 },
    { group: 'D组', rank: 6, region: '黑吉区', yoy: 7.5, achievementRate: 91.5, achievementRank: 6, change: 0 },
    { group: 'D组', rank: 7, region: '陕西区', yoy: 6.8, achievementRate: 89.2, achievementRank: 7, change: 0 },
    // E组
    { group: 'E组', rank: 1, region: '海南区', yoy: 11.8, achievementRate: 100.5, achievementRank: 1, change: 0 },
    { group: 'E组', rank: 2, region: '新疆区', yoy: 10.5, achievementRate: 98.2, achievementRank: 2, change: 0 },
    { group: 'E组', rank: 3, region: '山西区', yoy: 9.8, achievementRate: 96.5, achievementRank: 3, change: 0 },
    { group: 'E组', rank: 4, region: '广西区', yoy: 8.5, achievementRate: 94.2, achievementRank: 4, change: 0 },
    { group: 'E组', rank: 5, region: '甘青区', yoy: 7.2, achievementRate: 92.8, achievementRank: 5, change: 0 },
    { group: 'E组', rank: 6, region: '贵州区', yoy: 6.5, achievementRate: 90.5, achievementRank: 6, change: 0 },
    { group: 'E组', rank: 7, region: '内蒙古区', yoy: 5.8, achievementRate: 88.2, achievementRank: 7, change: 0 },
  ]
};

export const COLORS = {
  primary: '#00A86B',
  secondary1: '#66D9A8',
  secondary2: '#E8F5E9',
  accent: '#FF6B6B',
  textMain: '#333333',
  textSub: '#666666',
};
